[package]
name = "sgb_initializer"
version = "0.1.2"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
downloader = "0.2.7"
eyre = "0.6"
homedir = "0.3.3"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
tempfile = "3.12.0"
